---
title: "Israel COVID-19 report"
description: |
 The COVID-19 has lead to a pandamic, this report is based on Israel.
author:
  - name: Duan Qian
    url: https://etc5523-2021.github.io/blog-cici0702/
date: 08-29-2021
output:
  distill::distill_article:
   include:
     after_body: footer.html
   toc: true
   toc_depth: 3
   toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidycovid19)
library(zoo)
library(tidyverse)
library(gt)
library(plotly)
library(lubridate)
library(kableExtra)
library(DT)
library(sparkline)
library(rio)
library(scales)
library(rnaturalearth)
library(sf)
library(viridis)
library(dygraphs)
library(xts)
library(gganimate)
```

## dataset
```{r}
totaldat <- read.csv(here::here("dataset/owid-covid-data.csv"))

israel <- totaldat %>%
  filter(location == "Israel")

tot_age_gender <- read.csv(here::here("dataset/age_and_gender.csv")) %>%
  # recode the name
  mutate(gender = recode(gender,"זכר" = "male",
                         "נקבה" = "female")) %>%
  filter(gender == c("male","female"))

```



```{r}
# make a table of israel
# get the new cases and death data

israel_new <- israel %>%
  select(date, new_cases, new_deaths) %>%
  mutate(year = year(date),
         month = month(date))

israel_2020 <- israel_new %>%
  filter(year == "2020") %>%
  arrange(month)

israel_2020$Date <- with(israel_2020, sprintf("%d-%02d", year, month))


israel_2021 <- israel_new %>%
  filter(year == "2021") %>%
  arrange(month)

israel_2021$Date <- with(israel_2021, sprintf("%d-%02d", year, month))

israel_covid_total <- rbind(israel_2020,israel_2021)
```


```{r}
# sparkline
israel_covid_total %>%
  group_by(Date)%>%
  summarise(newcases = spk_chr(new_cases,
                           type = "line",
                           highlightLineColor = 'green', 
                           highlightSpotColor = 'yellow'),
            newcases_ = spk_chr(new_cases,
                           type = "box",
                           chartRangeMin=0, 
                           chartRangeMax=max(new_cases)),
            newdeaths = spk_chr(new_deaths,
                           type = "line",
                           highlightLineColor = 'green', 
                           highlightSpotColor = 'yellow'),
            newdeaths_ = spk_chr(new_deaths,
                           type = "box",
                           chartRangeMin=0, 
                           chartRangeMax=max(new_deaths)))%>%
  datatable(escape = F,
              rownames = F,
              options = list(fnDrawCallback = htmlwidgets::JS('function(){
                                                              HTMLWidgets.staticRender();
                                                              }'))
    ) %>% 
    spk_add_deps()
```




# draw map

```{r}
# data wrangling
asia <- totaldat %>%
  filter(continent == "Asia") %>%
  select(location, people_fully_vaccinated, population)

asia_map <- ne_countries(continent = "asia", returnclass = "sf", scale = "medium")%>% 
  select(name)

# recode tables
asia_map %>%
  anti_join(asia, by = c("name" = "location"))
asia_map <- asia_map %>%
  mutate(name = recode(name,
                       "Korea" = "South Korea"))
# join together
asia_map <- asia %>%
  right_join(asia_map, by = c("location" = "name"))

# clean
asia_vac <- asia_map %>%
  group_by(location) %>%
  na.omit()%>%
  filter(people_fully_vaccinated == max(people_fully_vaccinated))%>%
  mutate(vac_rate = round(people_fully_vaccinated/ population * 100,3))
```


```{r}
# draw map
map <- asia_vac %>%
  ggplot(group = location)+
  geom_sf(mapping = aes(geometry = geometry, fill = vac_rate, group = location), size = 0.3 )+
  theme_classic()+
  scale_fill_distiller(palette = "blues", na.value = "white", direction = 1)+
  scale_fill_viridis(option="viridis",breaks = c(0,10,30,50,60,70))+
  labs(fill = 'Fully vaccinated rate',
       color = 'Israel',
       title = 'Fully vaccinated rate of Covid in Asia(part)',
       x = NULL,
       y = NULL)+
  geom_point(x = 30, y = 31.04,shape = 11, size = 3, color = "red")

ggplotly(map)%>%
  layout(legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5))
```


```{r}
# compare the gender and age
# use dygraph for gender barchart for age
gender <- tot_age_gender %>%
  select(last_week_day, gender, weekly_tests_num, weekly_cases) %>%
  rename(`Weekly(date)` = last_week_day) %>%
  mutate(weekly_tests_num = as.numeric(weekly_tests_num),
         weekly_cases = as.numeric(weekly_cases),
        `Weekly(date)` = as.Date(`Weekly(date)`))%>%
  group_by(`Weekly(date)`, gender) %>%
  summarise(weekly_tests = sum(weekly_tests_num),
            weekly_cases = sum(weekly_cases))
```

```{r}
# draw dygraph
gender_cases <- gender %>%
  select(-weekly_tests)%>%
  pivot_wider(names_from = "gender",
              values_from = weekly_cases)
gender_cases <- gender_cases %>%
  xts(order.by = gender_cases$`Weekly(date)`)

dygraph(gender_cases, main = "The weekly newcases of genders in Israel") %>%
  dyAxis("y", label = "male") %>%
  dyAxis("y2", label = "female")%>%
  dySeries("male", axis = "y",stepPlot = TRUE,fillGraph = TRUE) %>%
  dySeries("female", axis = "y2", stepPlot = TRUE, color = "purple") %>%
  dyOptions(axisLineWidth = 1.5, drawGrid = FALSE,,fillAlpha = 0.5) %>%
  dyRangeSelector(height = 20) %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))
```

```{r}
# analysis the age group
age_group <- tot_age_gender %>%
  select(last_week_day, age_group, weekly_cases) %>%
  rename(`Weekly(date)` = last_week_day) %>%
  mutate(weekly_cases = as.numeric(weekly_cases),
        `Weekly(date)` = as.Date(`Weekly(date)`)) %>%
  mutate(year = year(`Weekly(date)`),
         month = month(`Weekly(date)`)) %>%
  na.omit() %>%
  group_by(year,month,age_group) %>%
  summarise(weekly_cases = sum(weekly_cases))

age_group$Date <- with(age_group, sprintf("%d-%02d", year, month))

```

```{r}
ggplot(age_group,aes(x = age_group , y = weekly_cases, fill = age_group)) +
  geom_bar(stat='identity')+
  theme_classic()+
  ggtitle("monthly new cases by age in Irsael")+
  scale_fill_manual(values = c("paleturquoise3","moccasin","lightsteelblue","salmon","lightskyblue3","sandybrown","darkolivegreen2","thistle2","gray85","orchid3","pink","yellow","hotpink","green","lightblue"))+
  transition_states(
    Date,
    transition_length = 3,
    state_length = 1
  ) +
  ease_aes('sine-in-out')
```

