---
title: "Data Description"
description: |
  A short description of the post.
author:
  - name: Duan Qian
    url: https://example.com/norajones
date: 08-29-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidycovid19)
library(zoo)
library(tidyverse)
library(gt)
library(plotly)
```


```{r}
df <- download_merged_data(cached = TRUE, silent = TRUE)
ireland <- df %>%
  filter(country == "Ireland")
```

```{r}
daily <- read.csv(here::here("all\ daily.csv")) %>%
  filter(location == "Ireland")

country <- read.csv(here::here("Covid19CountyStatisticsHPSCIreland.csv"))
```


```{r}
cleaned_ie <- ireland %>%
  select(2:6) %>%  
  mutate(newcases = confirmed - lag(confirmed),.before = deaths) %>%
  mutate(newdeaths = deaths - lag(deaths), .before = recovered)
```

```{r}
## add table
DT::datatable(cleaned_ie, options = list(pageLength = 3))
```

```{r}
# visualize the cases
p1 <- cleaned_ie %>%
  ggplot(aes(x = date, y = newcases))+
  geom_line()+
  theme_bw()

ggplotly(p1)
```


```{r}
## data cleaning
daily_vac <- daily %>%
  select(date,total_vaccinations, people_vaccinated, people_fully_vaccinated,population) %>%
  rename("people-get-1-dose" = people_vaccinated,
         "people-get-2-doses" = people_fully_vaccinated)%>%
  slice(n = (307:546))%>%
  mutate(date = as.Date(date)) %>%
  mutate(vaccination_rate=`people-get-2-doses`/ population*100) %>%
  filter(!is.na(total_vaccinations))

p2 <- ggplot(daily_vac,
       aes(x = date))+
  geom_area(aes(y = total_vaccinations, alpha = 0.3, fill = "total_vaccinations"), color = "blue")+
  geom_area(aes(y = `people-get-1-dose`, fill = "people-get-1-dose"),alpha = 0.3,color = "yellow")+
  geom_area(aes(y = `people-get-2-doses`, alpha = 0.3, fill = "people-get-2-doses"), color = "green")+
  theme_bw()+
  labs(title = "Vaccinations of Ireland",
       caption = "Source: Our World in Data")+
  theme(legend.position="bottom")
  
ggplotly(p2)
```





